<div class="wrapper-md bg-white b-b box-shadow">
    <h1 class="m-n font-thin h3">
        <span class="fa fa-globe"></span>
        <?= $this->translate('title.translation.dashboard', 'admin') ?>
    </h1>
</div>
<div class="wrapper-md">
    <div class="row">
        <?php foreach ($this->textDomains as $textDomain): ?>
            <div class="col-sm-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <a href="<?= $this->url('admin/translation/text-domain', ['text-domain' => $textDomain['text_domain']]) ?>">
                            <span class="panel-title">
                                <?= ucfirst($textDomain['text_domain']) ?>
                            </span>
                            <span class="panel-title pull-right text-muted">
                                200 Messages
                            </span>
                        </a>
                    </div>

                    <div class="panel-body">

                        <div class="progress m-t-sm ng-isolate-scope" max="max" value="dynamic" type="info">
                            <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="200" aria-valuetext="50%" style="width: 50%;">
                                <span style="white-space:nowrap;">50%</span>
                            </div>

                            <div class="progress-bar progress-bar-warning progress-bar-striped" style="width: 10%">
                                <span class="sr-only">10% Auto-Generated Messages</span>
                            </div>

                            <div class="progress-bar progress-bar-danger progress-bar-striped" style="width: 5%">
                                <span class="sr-only">5% Missing Translations</span>
                            </div>
                        </div>

                        <div class="list-group">
                            <a href="" class="list-group-item">
                                <i class="fa fa-chevron-right text-muted"></i>
                                <span class="badge bg-success">100</span>
                                <i class="fa fa-check fa-fw m-r-xs"></i> Translated Messages
                            </a>
                            <a href="" class="list-group-item">
                                <i class="fa fa-chevron-right text-muted"></i>
                                <span class="badge bg-danger">14</span>
                                <span class="badge bg-warning">20</span>
                                <i class="fa fa-question fa-fw m-r-xs"></i> Missing Translations
                            </a>
                        </div>


                    </div>
                </div>
            </div>
        <?php endforeach; ?>

        <div class="col-sm-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <span class="panel-title">
                        Auto-Generate Tests
                    </span>
                </div>
                <div class="panel-body">
                    <p>
                        <?= $this->translate('test.test', 'frontend'); ?><br>
                        <?= $this->translate('test.missing', 'frontend'); ?><br>
                        <?= $this->translate('test.test', 'mobile'); ?><br>
                        <?= $this->translate('test.missing', 'mobile'); ?><br>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
