<div class="wrapper-md bg-white b-b box-shadow">
    <h1 class="m-n font-thin h3">
        <span class="fa fa-globe"></span>
        <?= $this->translate('title.message', 'admin') ?>
    </h1>
</div>
<div class="wrapper-md">
    <form class="form-horizontal" role="form" action="<?= $this->url(null, [], [], true) ?>" method="post">
        <div class="panel panel-default">
            <div class="panel-body">
                <?= $this->formRender($this->createEditForm) ?>
            </div>
            <div class="panel-footer">
                <div class="form-group">
                    <div class="col-sm-offset-2 col-md-10">
                        <button type="submit" class="btn btn-primary">
                            <span class="fa fa-save"></span>
                            <?= $this->translate('button.save', 'admin') ?>
                        </button>

                        <?php if ($this->params()->fromRoute('isEditMode') == true): ?>
                            <button
                                type="button"
                                class="btn btn-danger dynamic-form-submit"
                                data-action="<?= $this->url('admin/translation/delete') ?>"
                                data-form-id="<?= $this->params()->fromRoute('id') ?>">
                                <span class="fa fa-trash-o"></span>
                                <?= $this->translate('button.delete', 'admin') ?>
                            </button>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
