<?php
$forceStTableReload = (strlen($this->params()->fromQuery('locale'))) || (strlen($this->params()->fromQuery('status'))) || strlen($this->params()->fromQuery('text-domain'));
?>
<?= $this->pageHeader($this->translate('title.translation.index', 'admin'), 'fa fa-globe') ?>
<div class="wrapper-md">
    <div class="panel panel-default">
        <div class="table-responsive" ng-controller="DataGridController"
             data-url="<?= $this->url(
                 'admin/translation/list'
             ) ?>">
            <table st-table="collection" st-pipe="callServer" class="table table-striped top-border-radius" st-persist="translation"<?= $forceStTableReload ? "st-persist-force-reload" : ""?>>
                <thead>
                <tr>
                    <th st-sort="message"><?= $this->translate('label.message', 'admin') ?></th>
                    <th st-sort="translation"><?= $this->translate('label.translation', 'admin') ?></th>
                    <th st-sort="locale"><?= $this->translate('label.locale', 'admin') ?></th>
                    <th st-sort="status"><?= $this->translate('label.status', 'admin') ?></th>
                    <th st-sort="textDomain"><?= $this->translate('label.textDomain', 'admin') ?></th>
                    <th></th>
                </tr>
                <tr>
                    <th>
                        <input st-search42="message" placeholder="search for message" class="input-sm form-control"
                               type="search"/>
                    </th>
                    <th>
                        <input st-search42="translation" placeholder="search for translation"
                               class="input-sm form-control" type="search"/>
                    </th>
                    <th>
                        <select st-search42="locale" class="form-control">
                            <option value="">All locales</option>
                            <?php foreach ($locales as $locale => $localeDisplay): ?>
                                <option value="<?= $locale ?>" <?= $this->params()->fromQuery('locale') == $locale
                                    ? 'selected'
                                    : '' ?>><?= $localeDisplay ?> (<?= $locale ?>)
                                </option>
                            <?php endforeach ?>
                        </select>
                    </th>
                    <th>
                        <select st-search42="status" class="form-control">
                            <option value="">All statuses</option>
                            <option value="auto" <?= $this->params()->fromQuery('status') == 'auto' ? 'selected'
                                : '' ?>><?= $this->translate('status.auto', 'admin') ?>
                            </option>
                            <option value="manual" <?= $this->params()->fromQuery('status') == 'manual' ? 'selected'
                                : '' ?>><?= $this->translate('status.manual', 'admin') ?>
                            </option>
                        </select>
                    </th>
                    <th>
                        <select st-search42="textDomain" class="form-control">
                            <option value="">All text domains</option>
                            <?php foreach ($textDomains as $textDomain): ?>
                                <option value="<?= $textDomain['text_domain'] ?>" <?=
                                $this->params()->fromQuery('text-domain') == $textDomain['text_domain']
                                    ? 'selected'
                                    : '' ?>><?= $textDomain['display_name'] ?>
                                </option>
                            <?php endforeach ?>
                        </select>
                    </th>
                    <th></th>
                </tr>
                </thead>
                <tbody ng-hide="isLoading">
                <tr ng-repeat="row in collection">
                    <td>{{row.message}}</td>
                    <td class="{{row.status == 'manual' && row.translation == null ? 'font-italic font-bold text-danger' : ''}}">
                        {{row.status == 'manual' && row.translation == null ? 'Missing translation' : row.translation}}
                    </td>
                    <td>
                        <span class="flag-icon flag-icon-{{row.locale.split('-')[1].toLowerCase()}}"></span>
                        {{row.locale}}
                    </td>
                    <td>{{row.status}}</td>
                    <td>{{row.textDomain}}</td>
                    <td class="text-right">
                        <?php if($this->permission('admin42')->isGranted('route/admin/translation/edit')): ?>
                        <a class="btn btn-info btn-xs"
                           ng-href="<?= $this->url(
                               "admin/translation/edit", ['id' => "{{ row.id }}"]
                           ) ?>">
                            <span class="fa fa-pencil"></span>
                        </a>
                        <?php endif; ?>
                        <?php if($this->permission('admin42')->isGranted('route/admin/translation/delete')): ?>
                            <delete
                                url="<?= $this->url('admin/translation/delete') ?>"
                                title="<?= $this->translate("translation.modal.delete.title", "admin") ?>"
                                size="xs"
                                content="<?= $this->translate("translation.modal.delete.content", "admin") ?>"
                                request-id="{{row.id}}"
                            >
                            </delete>
                        <?php endif; ?>
                    </td>
                </tr>
                </tbody>
                <tbody ng-show="isLoading">
                <tr>
                    <td colspan="6" class="text-center"><i class="fa fa-spin fa-refresh"></i></td>
                </tr>
                </tbody>
                <tfoot>
                <tr>
                    <td colspan="6" class="text-center">
                        <div st-pagination="" st-items-by-page="itemsByPage" st-displayed-pages="10"></div>
                    </td>
                </tr>
                </tfoot>
            </table>
        </div>
        <div class="panel-footer">
            <?php if($this->permission('admin42')->isGranted('route/admin/translation/add')): ?>
            <a class="btn btn-default"
               href="<?= $this->url('admin/translation/add') ?>">
                <span class="fa fa-plus-circle"></span>
                <?= $this->translate('button.message-key-add', 'admin') ?>
            </a>
            <?php endif; ?>
        </div>
    </div>
</div>
