<div class="wrapper-md bg-white b-b box-shadow">
    <h1 class="m-n font-thin h3">
        <span class="fa fa-globe"></span>
        <?= $this->translate('title.translation.index', 'admin') ?>
    </h1>
</div>
<div class="wrapper-md">
    <div class="panel panel-default">
        <div class="table-responsive" ng-controller="DataGridController"
             data-url="<?= $this->url(
                 'admin/translation/text-domain', ['text-domain' => $this->params()->fromRoute('text-domain')]
             ) ?>">
            <table st-table="collection" st-pipe="callServer" class="table table-striped top-border-radius">
                <thead>
                <tr>
                    <th st-sort="message"><?= $this->translate('label.message', 'admin') ?></th>
                    <th st-sort="translation"><?= $this->translate('label.translation', 'admin') ?></th>
                    <th st-sort="locale"><?= $this->translate('label.locale', 'admin') ?></th>
                    <th st-sort="textDomain"><?= $this->translate('label.textDomain', 'admin') ?></th>
                    <th st-sort="status"><?= $this->translate('label.status', 'admin') ?></th>
                </tr>
                <tr>
                    <th>
                        <input st-search="'message'" placeholder="search for message" class="input-sm form-control"
                               type="search"/>
                    </th>
                    <th>
                        <input st-search="'translation'" placeholder="search for translation"
                               class="input-sm form-control" type="search"/>
                    </th>
                    <th>
                        <input st-search="'locale'" placeholder="search for locale" class="input-sm form-control"
                               type="search"/>
                    </th>
                    <th>
                        <input st-search="'textDomain'" placeholder="search for textDomain"
                               class="input-sm form-control" type="search"
                               value="<?= $this->params()->fromRoute('text-domain') ?>"
                               st-value="<?= $this->params()->fromRoute('text-domain') ?>"/>
                    </th>
                    <th>
                        <input st-search="'status'" placeholder="search for status" class="input-sm form-control"
                               type="search"/>
                    </th>
                </tr>
                </thead>
                <tbody ng-hide="isLoading">
                <tr ng-repeat="row in collection">
                    <td>{{row.message}}</td>
                    <td>{{row.translation}}</td>
                    <td><span class="flag-icon flag-icon-{{row.locale.split('-')[1].toLowerCase()}}"></span> {{row.locale}}</td>
                    <td>{{row.textDomain}}</td>
                    <td>{{row.status}}</td>
                </tr>
                </tbody>
                <tbody ng-show="isLoading">
                <tr>
                    <td colspan="5" class="text-center"><i class="fa fa-spin fa-refresh"></i></td>
                </tr>
                </tbody>
                <tfoot>
                <tr>
                    <td colspan="5" class="text-center">
                        <div st-pagination="" st-items-by-page="itemsByPage" st-displayed-pages="1"></div>
                    </td>
                </tr>
                </tfoot>
            </table>
        </div>
        <div class="panel-footer">
            <a class="btn btn-default"
               href="<?= $this->url(
                   'admin/translation/text-domain/add', ['text-domain' => $this->params()->fromRoute('text-domain')]
               ) ?>">
                <span class="fa fa-plus-circle"></span>
                <?= $this->translate('button.message-key-add', 'admin') ?>
            </a>
        </div>
    </div>
</div>
